# -*- mode: ruby -*-
# vi: set ft=ruby :

# The ports on the host that you want to use to access the port on the guest.
# This must be greater than port 1024.
HTTP_HOST_PORT=8095
HTTP_GUEST_PORT=8080

APP_HOME_DIR="/opt/rest-interface"
Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "demo-centos7-rest-interface"
    vb.memory = "1024"
    vb.gui = false
  end

  # This prevents vagrant checking kernel and guest-additions for subsequent
  # vagrant up command executions, reducing the vm startup time
  if not isProvisioned() then
    if Vagrant.has_plugin?("vagrant-vbguest") then
      config.vbguest.installer_options = { allow_kernel_upgrade: true }
      config.vbguest.auto_update = true
    else
      raise 'vagrant-vbguest is not installed! Please install vagrant-vbguest plugin!'
    end
  else
    config.vbguest.auto_update = false
  end

  config.vm.network "forwarded_port",
    guest: HTTP_GUEST_PORT,
    host: HTTP_HOST_PORT,
    host_ip: "127.0.0.1"

  config.vm.provision "shell", name:"Pull scripts for REST interface", privileged:true, inline: <<-SHELL
    # These libraries could be moved or removed by the user if they were already covered
    yum install -y wget
    yum install -y unzip
    wget https://github.com/Moonshine-IDE/Vagrant-REST-Interface/releases/download/0.1.3/VagrantCRUD_centos7.zip

    unzip -d rest VagrantCRUD_centos7.zip
    mv rest/rest-interface-*.jar rest/rest-interface.jar
    chmod +x -R rest/
  SHELL

  config.vm.provision "shell",
    inline: "/bin/bash /home/vagrant/rest/provision.sh $1",
    privileged: false,
    args: [
      APP_HOME_DIR
    ]

  config.vm.provision "shell",
    inline: "/bin/bash /home/vagrant/rest/always.sh $1 $2 $3",
    privileged: false,
    run: "always",
    args: [
      HTTP_GUEST_PORT,
      APP_HOME_DIR,
      HTTP_HOST_PORT
    ]

end

def isProvisioned(vm_name='default', provider='virtualbox')
  File.exists?(File.join(File.dirname(__FILE__),".vagrant/machines/#{vm_name}/#{provider}/action_provision"))
end
