# -*- mode: ruby -*-
# vi: set ft=ruby :

# The ports on the host that you want to use to access the port on the guest.
# This must be greater than port 1024.
HTTP_HOST_PORT=8095
HTTP_GUEST_PORT=8080

APP_HOME_DIR="/opt/rest-interface"
ARTIFACT_NAME="rest-interface-0.1.jar"
Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
     vb.name = "rest-interface"
     vb.memory = "10224"
     vb.gui = false
   end

  config.vm.network "forwarded_port",
    guest: HTTP_GUEST_PORT,
    host: HTTP_HOST_PORT,
    host_ip: "127.0.0.1"

end
