name: Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Assign release version from version.properties to Env variable
        run: cat version.properties >> $GITHUB_ENV
      - name: Get rest-interface jar
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'Moonshine-IDE/REST-Interface'
          version: "tags/${{ env.interface_version }}"
          file: "rest-interface-${{ env.interface_version }}.jar"
          target: "src/rest-interface-${{ env.interface_version }}.jar"
          token: ${{ secrets.GH_TOKEN }}
      - name: Create Centos 7 zip
        uses: montudor/action-zip@v1
        with:
          args: zip -j VagrantCRUD_centos7.zip src/rest-interface-${{ env.interface_version }}.jar src/centos7/always.sh src/centos7/provision.sh src/resources/application.yml
      - name: Create Ubuntu zip
        uses: montudor/action-zip@v1
        with:
          args: zip -j VagrantCRUD_ubuntu.zip src/rest-interface-${{ env.interface_version }}.jar src/ubuntu/always.sh src/ubuntu/provision.sh src/resources/application.yml
      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: "v${{ env.release_version }}"
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Upload artifact for Centos 7
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: VagrantCRUD_centos7.zip
          asset_name: VagrantCRUD_centos7.zip
          asset_content_type: application/zip
      - name: Upload artifact for Ubuntu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: VagrantCRUD_ubuntu.zip
          asset_name: VagrantCRUD_ubuntu.zip
          asset_content_type: application/zip
