name: Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Assign release version from version.properties to Env variable
        run: cat version.properties >> $GITHUB_ENV
      - name: Get rest-interface jar
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'Moonshine-IDE/REST-Interface'
          version: "tags/${{ env.release_version }}"
          file: "rest-interface-${{ env.release_version }}.jar"
          target: "centos7/rest-interface-${{ env.release_version }}.jar"
          token: ${{ secrets.GH_TOKEN }}
      - name: Create zip
        uses: montudor/action-zip@v1
        with:
          args: zip -r centos7.zip centos7
      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: "v${{ env.release_version }}"
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: centos7.zip
          asset_name: centos7.zip
          asset_content_type: application/zip
